apiVersion: vmoperator.vmware.com/v1alpha1
kind: VirtualMachine
metadata:
  name: photon-vm-ecs11
  namespace: default
  annotations:
    vmoperator.vmware.com/image-supported-check: disable
spec:
  className: best-effort-small
  imageName: packages.vmware.com/photon/5.0/GA/ova/photon-hw15-5.0-dde71ec57.x86_64.ova
  powerState: poweredOn
  networkInterfaces:
  - networkName: "VM Network"
    ethernetCardType: "vmxnet3"

  vmMetadata:
    configMapName: user-data-photon
    transport: CloudInit
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: user-data-photon
    namespace: default
data:
  user-data: |
    #cloud-config
    ssh_pwauth: true
    users:
      - name: root
        sudo: ALL=(ALL) NOPASSWD:ALL
        lock_passwd: false
        passwd: 'Vk13YXJlMTIzIQo='
        shell: /bin/bash
    write_files:
      - content: |
          VMware Edge Cloud Orchestrator VM service says Hello World
        path: /helloworld
